### ISSUE TITLE
tnpm server后访问地址发现问题

### ISSUE THREAD

**Issue by ArcherZkd** [blackshow/hexo-theme-freemind.386#1]
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
WARN  No layout: index.html
WARN  No layout: index.html
WARN  No layout: index.html
WARN  No layout: index.html
WARN  No layout: index.html
WARN  No layout: index.html

**Comment by blackshow** [comment]
清理一下缓存试试，我之前出过这个问题

**Comment by ArcherZkd** [comment]
应该是clone下来  config文件没有，要自己添加，不过语言包还不知道怎么设置

**Comment by blackshow** [comment]
sorry,_config.yml添到.gitignore里了，语言包在hexo的配置文件里面设置,参考https://hexo.io/zh-cn/docs/internationalization.html   ,还是用英文比较好看，因为没找到中文的dos字体。。
