### ISSUE TITLE
How to get rid of heart icon in slogan line?

### ISSUE THREAD

**Issue by mmpg-x86** [blackshow/hexo-theme-freemind.386#10]
Is it possible to get rid of heart icon in slogan line?

**Comment by blackshow** [comment]
@gotoco Thanks。I had add a switch to turn off the heart icon or the slogan div.
plz pull the new commits.

**Comment by blackshow** [comment]
https://github.com/blackshow/hexo-theme-freemind.386/commit/33ac40d9bbebddb381ee3f6cbbbb44f5cf5aa1e5
