### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by i-zhen** [blackshow/hexo-theme-freemind.386#2]
主题很不错，汇报一个Bug：在safari浏览器上，read more按钮如果鼠标指针停留几秒钟后再点击会没有任何反应。

**Comment by blackshow** [comment]
这个bug我不知道怎么改，我原以为是因为<a>标签里面的type="button"导致的这个bug，但是去掉以后并没有改变，依然有这个bug，我试了一下bootstrap386并没有这个bug，但是我没有什么解决这个问题的思路，这位朋友有啥解决思路么，谢谢，虚心求教。

**Comment by makerggc** [comment]
大哥，能不能给个教程，装完了之后怎么改图标啊啥的，不会呀，如果没时间告诉我看哪些文档也行，比较喜欢这个主题  有个性
