### ISSUE TITLE
某个标签或者分类下没有显示所有文章也没有分页

### ISSUE THREAD

**Issue by Microndgt** [blackshow/hexo-theme-freemind.386#8]
![image](https://user-images.githubusercontent.com/15599445/34880005-09151c90-f7ea-11e7-84f5-119277371ec3.png)

**Comment by ieiang** [comment]
修改hexo的source/tags/index.md文件,添加 type: "tags" layout: "tags" 这两项就可以了 ，分类和标签一样步骤

**Comment by blackshow** [comment]
Duplicate of #5
